# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WordKik' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod 'SwiftyJSON'
   pod 'ObjectMapper'
   pod 'Alamofire'
   pod 'PINRemoteImage'
   pod 'SVProgressHUD' 	
   pod "MRLCircleChart"  
target 'WordKikTests' do
    inherit! :search_paths
end

  target 'WordKikUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
